<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="a" nsURI="http://eclipse.org/emf/emfstore/migration/edapt/test/a/2"
    nsPrefix="org.eclipse.emfstore.migration.edapt.test.a">
  <eClassifiers xsi:type="ecore:EClass" name="AClazz"/>
</ecore:EPackage>
